# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    # Set up environment for the project
    conda init bash
    conda env create -f pytorch-env.yml
    conda activate pytorch-env
  displayName: 'Environment creation'

- script: |
    # Run the training script
    python src/train.py
  displayName: 'Train pipeline'

- script: |
    # Run the tests
    pytest tests/
  displayName: 'Python tests'
